// ─────────────────────────────────────────────────────────────
//  Deployr — OFFLINE FALLBACK catalogue
//
//  The source of truth is now the local database (table `deployr.tools`,
//  see ../db.py), served via GET /api/tools. This list is only used when
//  the backend or DB is unreachable, so the dashboard still renders.
//  Keep it roughly in sync with the DB seed.
// ─────────────────────────────────────────────────────────────

window.DEPLOYR_TOOLS = [
  {
    id: "pdf-image-identifier",
    name: "PDF Image Identifier",
    tool: "picstalker",
    repo: "Ro-shni/PDF-IMAGE-IDENTIFIER",
    git_url: "https://github.com/Ro-shni/PDF-IMAGE-IDENTIFIER.git",
    branch: "main",
    entry_file: "app.py",
    app_var_name: "app",
    python_version: "python3.11",
    language: "Python · Flask",
    description: "Classifies PDF pages as Image, Text, or Image+Text and uploads to Wikimedia Commons.",
    url: "https://picstalker.toolforge.org/",
    live: true,            // ← real tool, exercises the backend
    status: "unknown",
    lastDeploy: "2026-06-25T14:02:00Z",
  },
  {
    id: "citation-hunt",
    name: "Citation Hunt",
    tool: "citation-hunt",
    repo: "wikimedia/citation-hunt",
    git_url: "https://github.com/wikimedia/citation-hunt.git",
    branch: "main",
    entry_file: "app.py",
    app_var_name: "app",
    python_version: "python3.11",
    language: "Python · Flask",
    description: "Surfaces unsourced Wikipedia snippets that need citations.",
    url: "https://citationhunt.toolforge.org/",
    status: "running",
    lastDeploy: "2026-06-20T09:15:00Z",
  },
  {
    id: "commons-uploader",
    name: "Commons Batch Uploader",
    tool: "commons-uploader",
    repo: "Ro-shni/commons-uploader",
    git_url: "https://github.com/Ro-shni/commons-uploader.git",
    branch: "main",
    entry_file: "server.py",
    app_var_name: "app",
    python_version: "python3.11",
    language: "Python",
    description: "Bulk-uploads freely licensed media to Wikimedia Commons with OAuth.",
    url: "https://commons-uploader.toolforge.org/",
    status: "stopped",
    lastDeploy: "2026-06-12T18:40:00Z",
  },
  {
    id: "wikitrends",
    name: "WikiTrends",
    tool: "wikitrends",
    repo: "Ro-shni/wikitrends",
    git_url: "https://github.com/Ro-shni/wikitrends.git",
    branch: "develop",
    entry_file: "wsgi.py",
    app_var_name: "app",
    python_version: "python3.11",
    language: "Python · Flask",
    description: "Dashboards for trending article pageviews across language editions.",
    url: "https://wikitrends.toolforge.org/",
    status: "running",
    lastDeploy: "2026-06-24T11:30:00Z",
  },
  {
    id: "lexeme-forms",
    name: "Lexeme Forms",
    tool: "lexeme-forms",
    repo: "wikimedia/lexeme-forms",
    git_url: "https://github.com/wikimedia/lexeme-forms.git",
    branch: "main",
    entry_file: "app.py",
    app_var_name: "app",
    python_version: "python3.11",
    language: "Python · Flask",
    description: "Guided creation of Wikidata lexeme forms from templates.",
    url: "https://lexeme-forms.toolforge.org/",
    status: "stopped",
    lastDeploy: "2026-05-30T08:00:00Z",
  },
  {
    id: "depictor",
    name: "Depictor",
    tool: "depictor",
    repo: "Ro-shni/depictor",
    git_url: "https://github.com/Ro-shni/depictor.git",
    branch: "main",
    entry_file: "app.py",
    app_var_name: "app",
    python_version: "python3.11",
    language: "Python · Flask",
    description: "Crowdsources structured-data depicts statements for Commons images.",
    url: "https://depictor.toolforge.org/",
    status: "deploying",
    lastDeploy: "2026-06-26T07:45:00Z",
  },
];
