"""test migration run

Revision ID: 7d5e42af539b
Revises: 26b943deaaa8
Create Date: 2026-06-27 15:54:29.979640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d5e42af539b'
down_revision = '26b943deaaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagsy', sa.String(length=255), nullable=True))
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('tagsy')

    # ### end Alembic commands ###
